version: '3.8'

services:
  postgres:
    image: postgres:14.15-alpine3.21
    container_name: musiclib_postgres
    environment:
      POSTGRES_USER: musiclib
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: musiclib
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  musiclib:
    container_name: musiclib
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env.docker

volumes:
  postgres_data: